### ISSUE TITLE
Column offsets function

### ISSUE THREAD

**Issue by zapmedia** [whatsnewsaes/Skeleton-Sass#11] opened 2015-01-24 16:54 UTC
The current function for column-offset-length is missing the addition of $column-margin

**Comment by benhinchley** [comment] 2015-01-25 05:50
@zapmedia The math is still correct though @whatsnewsaes Would you like me to work on a fix to include the `$column-margin` variable?

**Comment by benhinchley** [comment] 2015-01-25 06:23
After looking at the math a bit, I better understand why the `$column-margin` variable is missing from the `grid-offset-length` function. 


In the `grid-column-width` function, we minus the `$column-margin` variable from the result of the following `$column-width * $n + ($n/3)` to give us the width of the variable.
```scss
@function grid-column-width($n) {
  @return $column-width * $n + ($n/3) - ($column-margin);
}
```
_function re-written for clarity of math_

---

So by omitting `$column-margin` from the `grid-offset-length` function is basically the same as writing 
```scss
@function grid-offset-length($n) {
  @return ($column-width * $n + ($n/3) - ($column-margin)) + $column-margin;
}
```

or subbing out the first set of parentheses for `grid-column-width($n)` gives the same result

```scss
@function grid-offset-length-new($n) {
  @return grid-column-width($n) + $column-margin;
}
```

---

which imho doesn't make a lot of sense and just omitting the variable completely from the  `grid-offset-length` function completely _(like the function currently is)_, makes the math a lot simpler and less repetitive. 

```scss
@function grid-offset-length($n) {
  @return percentage(($column-width * $n  + ($n/3)) / 100);
}
```

Hopefully that makes sense, let me know if anything doesn't

**Comment by zapmedia** [comment] 2015-01-25 12:54
Yes, I understand the math, however without adding $column-margin the columns do not stretch across the full length of the container. Maybe I'm missing something. 

I'm using the following: @return percentage(($column-width * $n  + ($n/3) + 4 ) / 100);

**Comment by benhinchley** [comment] 2015-01-25 23:55
Interesting as it seems to work fine for me, if you check out this [gist on SassMeister.](http://sassmeister.com/gist/2cec16bcf86138203e24), you should be able to play around with it a bit easier, shows how the current code works. I added your code to it as well, and you can see how your function code pushes the the column outside of the container. Hope that helps.

**Comment by zapmedia** [comment] 2015-01-26 08:46
Yes is works for me too, only if I have no other div column within the same container / row.

However you will see from the following http://sassmeister.com/gist/428bc40437f76efd2fbe
that if the container has more than one column div, it will not fill the length of the container.

This is also true for the default Skeleton CSS.

Maybe, I am using Skeleton incorrectly.

**Comment by benhinchley** [comment] 2015-01-27 02:03
Totally see your point now, I have never tried to offset the column with another column in the row. Maybe we should bring this issue into the [Skeleton CSS](https://github.com/dhg/Skeleton)?

**Comment by benhinchley** [comment] 2015-02-03 04:12
@zapmedia this seems to have been fixed in PR #13

**Comment by haxiomic** [comment] 2015-02-03 11:59
@benhinchley I'm not certain the problem is fixed, I suspect there's an issue in Skeleton CSS - offsets don't behave as I'd expect using the default skeleton.css - columns that are offset don't seem to line up with the rest of the grid nicely. Checkout this demo to see what I mean [http://sassmeister.com/gist/d4d0a9ea7135eb851b7c](http://sassmeister.com/gist/d4d0a9ea7135eb851b7c)

If you look at the second row of the offset examples, we've got a 'one' column, followed by a 'one-half' which is offset by five, so adding up the total columns used, 1 + 5 empty + 6 = 12, so it should fill the entire width, but it doesn't. (The demo is using the latest skeleton.scss, but the result is the same if you use skeleton.css). I'm not sure what @dhg was going for with this, but the must be some reason why it works this way.

I've modified the way offsets are calculated and you can see this in the demo - all the columns now line up with each other. I left this out of PR #13 because it doesn't exactly reproduce the result from skeleton.css and it requires adding :first-child selectors to each offset-by-* rule which is a fair bit of additional code.

**Comment by whatsnewsaes** [comment] 2015-03-28 23:17
Hey guys,

put together a little project called boneless This will give us the freedom to be able to improve/expand without feeling tied down.

**Comment by haxiomic** [comment] 2015-03-29 21:43
Nice idea :+1:

**Comment by whatsnewsaes** [comment] 2015-03-29 22:29
@haxiomic If you have any input or would like to help shape the direction, hit me up either by email or on the [boneless](https://github.com/whatsnewsaes/Boneless) repo.

**Closed** 2015-06-15 16:37 UTC
Labels: bug
